version: '3.8'
services:
  frontend:
    build:
      context: ./frontend-project
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend-project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev
  backend:
    build:
      context: ./backend-project
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend-project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
